name: pethome_mobileapp
description: "Mobile application for PetHome project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter

  flutter_otp_text_field: ^1.1.3+2
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.1.0
  http: ^1.2.1
  image_picker: ^1.1.1
  intl: ^0.17.0
  readmore: ^2.0.0
  shared_preferences: ^2.2.3
  top_snackbar_flutter: ^3.1.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/pictures/
